### PR TITLE
Update zh-Hans to the 2021 version

### PR DESCRIPTION
**Pull request by kkbruce**
@MoienTajik 

1. Update zh-Hans to the 2021 version.
2. fixed some zh-Hant typo issue.
3. zh-Hans and zh-Hant about Microsoft document link add my MS docs Id. This can increase my MS contribution, please allow me to do so.
3. ReadMe.md update SQL Server link to 2019.

### CODE REVIEW

**Review by MoienTajik — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution. I really appreciate that!
Please remove `WT.mc_id` from URLs as we're an open-source library and we shouldn't include any credits in the project.

**Comment by kkbruce** [comment]
remove all it. confirm it.

**Review by MoienTajik — APPROVED** [review]

**Comment by MoienTajik** [comment]
Thanks!
Could you resolve conflicts from this branch to `master` branch?

**Comment by kkbruce** [comment]
@MoienTajik resolved conflict.

**Review by MoienTajik — APPROVED** [review]

**Pull request merged**
