### PR TITLE
Here is my suggested list

### PR DESCRIPTION
**Pull request by mo-esmp**
- [Practical ASP.NET Core](https://github.com/dodyg/practical-aspnetcore), tones of practical ASP.NET Core samples
 - Some great DI containers based [palmmedia benchmark](https://www.palmmedia.de/Blog/2011/8/30/ioc-container-benchmark-performance-comparison) - [Simple Injector](https://simpleinjector.org/), [LightInject](https://github.com/seesharper/LightInject), [DryIoc](https://github.com/dadhi/DryIoc)
- [MQTTnet](https://github.com/chkr1011/MQTTnet), is a high-performance .NET library for MQTT based communication. It provides a MQTT client and a MQTT server (broker)
- [Bogus](https://github.com/bchavez/Bogus), yet another great fake data generator
- MicroServices tools ([Tye](https://github.com/dotnet/tye),[ dapr](https://github.com/dapr/dapr), [ocelote](https://github.com/ThreeMammals/Ocelot)), library, tools and api gateway that make life more easier to develop Microservices 
- And also fix readme file formatting

### CODE REVIEW

**Comment by mo-esmp** [comment]
Feel free to close this pull request if you think it's not aligned with the main roadmap.

**Comment by MoienTajik** [comment]
Thanks, @mo-esmp. 
Could you change the xmind and png file accordingly to this change?

**Comment by mo-esmp** [comment]
Here is updated png file to review, but I have no idea where to put `Practical ASP.NET Core`

ASP NET Core Developer in 2019

**Comment by MoienTajik** [comment]
Maybe we could place the Practical ASP.NET Core in a learning resources section in the readme section and not directly in the roadmap image?

**Comment by mo-esmp** [comment]
Yes, it's a good idea, I agree with you.

**Pull request closed without merging**
